import { createClient } from "@supabase/supabase-js";
import type { NextPage } from "next";
import Head from "next/head";
import { Gallery } from "../components";
import styles from "../styles/Home.module.css";
import { supabaseAdmin } from "../utils/supabase";

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery data={data} />
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const { data } = await supabaseAdmin.from("images").select("*").order("id");

  return {
    props: {
      data,
    },
  };
}
